
all: hpfdcli

hpfdcli: hpfdcli.c ../appsupport/libhpfeeds/src/hpfeeds.c ../appsupport/libhpfeeds/src/sha1.c
	gcc -o hpfdcli hpfdcli.c ../appsupport/libhpfeeds/src/hpfeeds.c ../appsupport/libhpfeeds/src/sha1.c -I../appsupport/libhpfeeds/include
